project:
  type: website
  output-dir: docs

website:
  title: "Quantitative Geographie: Mobile Gesellschaft"
  sidebar:
    style: docked
    search: true
    contents:
      - href: index.qmd
        text: Intro
      - 01_basics.qmd
      - 02_data_manipulation.qmd
      - 03_sequenzanalyse.qmd
      - 04_mapping.qmd

format:
  html:
    theme:
      - zephyr
      - brand
    css: styles.css
    logo: images/logo.jpg
    toc: true
    page-layout: article

